# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.ManyToManyField(blank=True, help_text='Select a genre for the film', to='catalog.Genre'),
        ),
    ]
