# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20171114_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='due_back',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
