# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20171114_1825'),
        ('catalog', '0004_film_borrower'),
    ]

    operations = [
    ]
