# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 17:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_merge_20171115_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
